package com.atme8.activity.domain.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Activity extends AbstractEntity implements Serializable {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity.title
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity.reg_deadline
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private Date regDeadline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity.address
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity.upper_limit
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private Integer upperLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_activity.is_free
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private Boolean isFree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity.title
	 * @return  the value of t_activity.title
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity.title
	 * @param title  the value for t_activity.title
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity.reg_deadline
	 * @return  the value of t_activity.reg_deadline
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public Date getRegDeadline() {
		return regDeadline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity.reg_deadline
	 * @param regDeadline  the value for t_activity.reg_deadline
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setRegDeadline(Date regDeadline) {
		this.regDeadline = regDeadline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity.address
	 * @return  the value of t_activity.address
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity.address
	 * @param address  the value for t_activity.address
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity.upper_limit
	 * @return  the value of t_activity.upper_limit
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public Integer getUpperLimit() {
		return upperLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity.upper_limit
	 * @param upperLimit  the value for t_activity.upper_limit
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setUpperLimit(Integer upperLimit) {
		this.upperLimit = upperLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_activity.is_free
	 * @return  the value of t_activity.is_free
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public Boolean getIsFree() {
		return isFree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_activity.is_free
	 * @param isFree  the value for t_activity.is_free
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setIsFree(Boolean isFree) {
		this.isFree = isFree;
	}

	private List<ActivityRegField> regFields;
	
	/**
	 * regFields getter method
	 * @return the regFields
	 */
	public List<ActivityRegField> getRegFields() {
		return regFields;
	}

	/**
	 * regFields setter method
	 * @param regFields the regFields to set
	 */
	public void setRegFields(List<ActivityRegField> regFields) {
		this.regFields = regFields;
	}
	
	private List<ActStage> stages;
	
	/**
	 * stages getter method
	 * @return the stages
	 */
	public List<ActStage> getStages() {
		return stages;
	}

	/**
	 * stages setter method
	 * @param stages the stages to set
	 */
	public void setStages(List<ActStage> stages) {
		this.stages = stages;
		if (stages != null) {
			setBeginTime(stages.get(0).getBegin());
			setEndTime(stages.get(stages.size()-1).getEnd());
		}
	}

	private Date beginTime;

	private Date endTime;

	public Date getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
}
