package com.atme8.activity.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class ActStage extends AbstractEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_act_stage.act_id
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	private String actId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_act_stage.name
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_act_stage.begin
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	private Date begin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_act_stage.end
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	private Date end;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_act_stage.order1
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	private Integer order1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_act_stage.act_id
	 * @return  the value of t_act_stage.act_id
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public String getActId() {
		return actId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_act_stage.act_id
	 * @param actId  the value for t_act_stage.act_id
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public void setActId(String actId) {
		this.actId = actId == null ? null : actId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_act_stage.name
	 * @return  the value of t_act_stage.name
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_act_stage.name
	 * @param name  the value for t_act_stage.name
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_act_stage.begin
	 * @return  the value of t_act_stage.begin
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public Date getBegin() {
		return begin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_act_stage.begin
	 * @param begin  the value for t_act_stage.begin
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public void setBegin(Date begin) {
		this.begin = begin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_act_stage.end
	 * @return  the value of t_act_stage.end
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public Date getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_act_stage.end
	 * @param end  the value for t_act_stage.end
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public void setEnd(Date end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_act_stage.order1
	 * @return  the value of t_act_stage.order1
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public Integer getOrder1() {
		return order1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_act_stage.order1
	 * @param order1  the value for t_act_stage.order1
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	public void setOrder1(Integer order1) {
		this.order1 = order1;
	}
}