package com.atme8.activity.domain.entity;

import java.io.Serializable;
import java.util.List;

public class Registration extends AbstractEntity implements Serializable {
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_registration.user_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_registration.act_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String actId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_registration.user_id
	 * @return  the value of t_registration.user_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_registration.user_id
	 * @param userId  the value for t_registration.user_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_registration.act_id
	 * @return  the value of t_registration.act_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getActId() {
		return actId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_registration.act_id
	 * @param actId  the value for t_registration.act_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setActId(String actId) {
		this.actId = actId == null ? null : actId.trim();
	}

	private List<RegistrationInfo> values;
	
	public List<RegistrationInfo> getValues() {
		return values;
	}

	public void setValues(List<RegistrationInfo> values) {
		this.values = values;
	}
}