package com.atme8.activity.domain.entity;

import java.io.Serializable;

public class RegistrationInfoKey extends AbstractEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_registration_info.reg_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String regId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_registration_info.field_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String fieldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_registration_info.reg_id
	 * @return  the value of t_registration_info.reg_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getRegId() {
		return regId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_registration_info.reg_id
	 * @param regId  the value for t_registration_info.reg_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setRegId(String regId) {
		this.regId = regId == null ? null : regId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_registration_info.field_id
	 * @return  the value of t_registration_info.field_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getFieldId() {
		return fieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_registration_info.field_id
	 * @param fieldId  the value for t_registration_info.field_id
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setFieldId(String fieldId) {
		this.fieldId = fieldId == null ? null : fieldId.trim();
	}
}