package com.atme8.activity.domain.entity;

import java.io.Serializable;

public class RegistrationInfo extends RegistrationInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_registration_info.value
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_registration_info.value
	 * @return  the value of t_registration_info.value
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_registration_info.value
	 * @param value  the value for t_registration_info.value
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}
	
	
}