package com.atme8.activity.domain.entity;

import java.io.Serializable;

public class SystemSetting extends AbstractEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_system_setting.name
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_system_setting.value
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_system_setting.is_enable
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private Boolean isEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_system_setting
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_system_setting.name
	 * @return  the value of t_system_setting.name
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_system_setting.name
	 * @param name  the value for t_system_setting.name
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_system_setting.value
	 * @return  the value of t_system_setting.value
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_system_setting.value
	 * @param value  the value for t_system_setting.value
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_system_setting.is_enable
	 * @return  the value of t_system_setting.is_enable
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public Boolean getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_system_setting.is_enable
	 * @param isEnable  the value for t_system_setting.is_enable
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}
}