package com.atme8.activity.domain.dao.mybatis.mapper;

import com.atme8.activity.domain.dao.mybatis.BaseMapper;
import com.atme8.activity.domain.entity.Activity;
import com.atme8.activity.domain.entity.ActivityExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ActivityMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int countByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int deleteByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int insert(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int insertSelective(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	List<Activity> selectByExample(ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	Activity selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Activity record,
			@Param("example") ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByExample(@Param("record") Activity record, @Param("example") ActivityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByPrimaryKeySelective(Activity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_activity
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByPrimaryKey(Activity record);
}