package com.atme8.activity.domain.dao.mybatis.mapper;

import com.atme8.activity.domain.entity.ActivityRegField;
import com.atme8.activity.domain.entity.ActivityRegFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityRegFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int countByExample(ActivityRegFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int deleteByExample(ActivityRegFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int insert(ActivityRegField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int insertSelective(ActivityRegField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    List<ActivityRegField> selectByExample(ActivityRegFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    ActivityRegField selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") ActivityRegField record, @Param("example") ActivityRegFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int updateByExample(@Param("record") ActivityRegField record, @Param("example") ActivityRegFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int updateByPrimaryKeySelective(ActivityRegField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_reg_field
     *
     * @mbggenerated Fri Nov 13 09:33:39 CST 2015
     */
    int updateByPrimaryKey(ActivityRegField record);
}