package com.atme8.activity.domain.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.atme8.activity.domain.dao.mybatis.BaseMapper;
import com.atme8.activity.domain.entity.ActStage;
import com.atme8.activity.domain.entity.ActStageExample;

public interface ActStageMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int countByExample(ActStageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int deleteByExample(ActStageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int insert(ActStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int insertSelective(ActStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	List<ActStage> selectByExample(ActStageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	ActStage selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ActStage record,
			@Param("example") ActStageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int updateByExample(@Param("record") ActStage record, @Param("example") ActStageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int updateByPrimaryKeySelective(ActStage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_act_stage
	 * @mbggenerated  Mon Sep 21 15:17:10 CST 2015
	 */
	int updateByPrimaryKey(ActStage record);
}