package com.atme8.activity.domain.dao.mybatis.mapper;

import com.atme8.activity.domain.dao.mybatis.BaseMapper;
import com.atme8.activity.domain.entity.Registration;
import com.atme8.activity.domain.entity.RegistrationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RegistrationMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int countByExample(RegistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int deleteByExample(RegistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int insert(Registration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int insertSelective(Registration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	List<Registration> selectByExample(RegistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	Registration selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Registration record,
			@Param("example") RegistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByExample(@Param("record") Registration record,
			@Param("example") RegistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByPrimaryKeySelective(Registration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByPrimaryKey(Registration record);
}