package com.atme8.activity.domain.dao.mybatis.mapper;

import com.atme8.activity.domain.dao.mybatis.BaseMapper;
import com.atme8.activity.domain.entity.RegistrationInfo;
import com.atme8.activity.domain.entity.RegistrationInfoExample;
import com.atme8.activity.domain.entity.RegistrationInfoKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RegistrationInfoMapper extends BaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int countByExample(RegistrationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int deleteByExample(RegistrationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int deleteByPrimaryKey(RegistrationInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int insert(RegistrationInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int insertSelective(RegistrationInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	List<RegistrationInfo> selectByExampleWithBLOBs(RegistrationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	List<RegistrationInfo> selectByExample(RegistrationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	RegistrationInfo selectByPrimaryKey(RegistrationInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") RegistrationInfo record,
			@Param("example") RegistrationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") RegistrationInfo record,
			@Param("example") RegistrationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByExample(@Param("record") RegistrationInfo record,
			@Param("example") RegistrationInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByPrimaryKeySelective(RegistrationInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(RegistrationInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_registration_info
	 * @mbggenerated  Mon Nov 09 16:48:16 CST 2015
	 */
	int updateByPrimaryKey(RegistrationInfo record);
}